# Generated by Django 4.2.20 on 2025-05-01 20:52

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.region'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('id', 'region')},
        ),
    ]
