# Generated by Django 4.2.20 on 2025-05-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_region_alter_member_managers_member_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.region'),
            preserve_default=False,
        ),
    ]
